version: "3.5"

networks:
  api:
    name: api_test
    driver: bridge

services:
  portainer:
    image: portainer/portainer
    volumes:
      - ./.portainer_data:/data portainer/portainer
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 9090:9000
      - 8000:8000
    networks:
      - api

  mysql:
    image: library/mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
    volumes:
      - ./.mysqldata:/var/lib/mysql
    networks:
      - api

  adminer:
    image: adminer:latest
    ports:
      - 8050:8080
    networks:
      - api

  nginx:
    image: nginx:latest
    ports:
      - 8080:80
    volumes:
      - ./:/www
      - ./.docker/nginx/my.conf:/etc/nginx/conf.d/default.conf
      - ./.nginx/logs:/logs
    networks:
      - api
    depends_on:
      - php

  php:
    build:
      context: .docker/
      dockerfile: Dockerfile
    volumes:
      - ./:/www
    networks:
      - api
    depends_on:
      - mysql

